
"use client";

import { handleGenerateSummary } from "@/lib/actions";
import { useState } from "react";
import { Button } from "../ui/button";
import { Loader2, Sparkles } from "lucide-react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "../ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../ui/card";

export function PublicationSummary({ publicationText }: { publicationText: string }) {
    const [summary, setSummary] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [isOpen, setIsOpen] = useState(false);
    const { toast } = useToast();

    const onGenerate = async () => {
        if (summary) {
            setIsOpen(true);
            return;
        }

        setIsLoading(true);
        setIsOpen(true);
        const result = await handleGenerateSummary(publicationText);
        setIsLoading(false);

        if (result.error) {
            toast({
                title: "Error",
                description: result.error,
                variant: "destructive"
            });
            setIsOpen(false);
        } else if (result.data) {
            setSummary(result.data);
        }
    };

    return (
        <Dialog open={isOpen} onOpenChange={setIsOpen}>
            <Card className="bg-secondary/50">
                <CardHeader>
                    <CardTitle className="flex items-center gap-2">
                        <Sparkles className="h-5 w-5 text-primary"/>
                        AI-Powered Summary
                    </CardTitle>
                    <CardDescription>
                        Get a simplified summary of this publication.
                    </CardDescription>
                </CardHeader>
                <CardContent>
                    <Button onClick={onGenerate} className="w-full">
                        {isLoading ? (
                            <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                        ) : (
                            <Sparkles className="mr-2 h-4 w-4" />
                        )}
                        {summary ? "View Summary" : "Generate Summary"}
                    </Button>
                </CardContent>
            </Card>

            <DialogContent className="sm:max-w-[625px]">
                <DialogHeader>
                    <DialogTitle>AI-Generated Summary</DialogTitle>
                    <DialogDescription>
                        This summary was generated by AI and may not be fully accurate. Always consult the original text.
                    </DialogDescription>
                </DialogHeader>
                <div className="py-4">
                    {isLoading ? (
                        <div className="flex justify-center items-center h-40">
                            <Loader2 className="h-8 w-8 animate-spin text-primary" />
                        </div>
                    ) : (
                        <p className="leading-relaxed text-sm text-muted-foreground">{summary}</p>
                    )}
                </div>
            </DialogContent>
        </Dialog>
    );
}
